name: AVAnnounce
main: AVENDA\Announce
version: 1.0
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: AVENDA
commands:
  확성기:
    usage: /확성기 [할말]
    description: AVAnnounce Commands
    permission: AvAnnounce.command

permissions:
  AvAnnounce.command:
    default: true
